{{- if and .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-controller
  labels:
    app.kubernetes.io/instance: {{ .Values.installationNamespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: {{ .Values.installationNamespace }}
  - kind: ServiceAccount
    name: helm-controller
    namespace: {{ .Values.installationNamespace }}
  - kind: ServiceAccount
    name: source-controller
    namespace: {{ .Values.installationNamespace }}
  - kind: ServiceAccount
    name: notification-controller
    namespace: {{ .Values.installationNamespace }}
  - kind: ServiceAccount
    name: image-reflector-controller
    namespace: {{ .Values.installationNamespace }}
  - kind: ServiceAccount
    name: image-automation-controller
    namespace: {{ .Values.installationNamespace }}
{{- end }}
