apiVersion: fluxcd.open-cluster-management.io/v1alpha1
kind: FluxCDConfig
metadata:
  labels:
    app.kubernetes.io/name: fluxcdconfig
    app.kubernetes.io/instance: fluxcdconfig-sample
    app.kubernetes.io/part-of: api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: api
  name: fluxcdconfig
  namespace: open-cluster-management
spec:
  installCRDs: true
  helmController:
    create: true
    labels:
      ace.appscode.com/managed: "true"
  sourceController:
    create: true
    labels:
      ace.appscode.com/managed: "true"
  imageAutomationController:
    create: false
  imageReflectionController:
    create: false
  kustomizeController:
    create: false
  notificationController:
    create: false
