kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: busybox
  template:
    metadata:
      labels:
        addon: busybox
    spec:
      containers:
        - name: fluxcd
          image: {{ .Values.global.imageOverrides.helloWorldHelm }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - "sleep"
            - "3600"